import type { ResearchResponse } from "@/components/portfolio/portfolio-research"
import type { SummaryResp } from "@/components/portfolio/portfolio-summary-report"

const now = new Date()

export const demoPortfolio = {
  id: "demo-portfolio",
  name: "Global Growth Demo",
  description: "Preview portfolio for demo visitors",
  created_at: "2024-02-10T12:00:00.000Z",
  updated_at: now.toISOString(),
  portfolio_holdings: [
    { id: "h1", ticker: "AAPL", weight: 12.5, shares: 80, purchase_price: 142 },
    { id: "h2", ticker: "MSFT", weight: 10.2, shares: 60, purchase_price: 278 },
    { id: "h3", ticker: "NVDA", weight: 9.4, shares: 35, purchase_price: 188 },
    { id: "h4", ticker: "GOOGL", weight: 8.1, shares: 55, purchase_price: 122 },
    { id: "h5", ticker: "V", weight: 6.8, shares: 40, purchase_price: 212 },
    { id: "h6", ticker: "TSLA", weight: 5.6, shares: 25, purchase_price: 242 },
    { id: "h7", ticker: "JNJ", weight: 4.2, shares: 30, purchase_price: 162 },
    { id: "h8", ticker: "XLE", weight: 4.9, shares: 45, purchase_price: 82 },
  ],
}

export const demoAnalysis = {
  meta: { refreshedAt: "2025-01-07T09:00:00.000Z" },
  performanceMeta: { benchmark: "S&P 500 (^GSPC)" },
  metrics: {
    sortinoRatio: 1.42,
    portfolioBetaSpx: 1.05,
    spxBeta: 1.0,
    betaDiff: 0.05,
  },
  sectors: [
    { sector: "Technology", allocation: 32.5, target: 28.0, color: "#2563eb" },
    { sector: "Communication Services", allocation: 12.2, target: 11.0, color: "#7c3aed" },
    { sector: "Consumer Discretionary", allocation: 14.8, target: 12.0, color: "#16a34a" },
    { sector: "Financials", allocation: 11.0, target: 13.0, color: "#f59e0b" },
    { sector: "Healthcare", allocation: 9.6, target: 13.5, color: "#0ea5e9" },
    { sector: "Energy", allocation: 7.1, target: 5.0, color: "#f97316" },
    { sector: "Industrials", allocation: 7.8, target: 9.0, color: "#6366f1" },
    { sector: "Materials", allocation: 5.0, target: 4.5, color: "#14b8a6" },
  ],
  risk: {
    concentration: { level: "Moderate", largestPositionPct: 9.8 },
    diversification: { score: 7.4, holdings: 18, top2Pct: 17.3 },
    beta: { level: "Slightly Above Market" },
  },
  dividends: {
    year: 2025,
    totalIncome: 1860,
    monthlyTotals: [
      { key: "jan", label: "Jan", amount: 120 },
      { key: "feb", label: "Feb", amount: 135 },
      { key: "mar", label: "Mar", amount: 155 },
      { key: "apr", label: "Apr", amount: 160 },
      { key: "may", label: "May", amount: 150 },
      { key: "jun", label: "Jun", amount: 170 },
      { key: "jul", label: "Jul", amount: 175 },
      { key: "aug", label: "Aug", amount: 180 },
      { key: "sep", label: "Sep", amount: 165 },
      { key: "oct", label: "Oct", amount: 150 },
      { key: "nov", label: "Nov", amount: 130 },
      { key: "dec", label: "Dec", amount: 120 },
    ],
    quarterlyTotals: [
      { key: "q1", label: "Q1", amount: 410 },
      { key: "q2", label: "Q2", amount: 480 },
      { key: "q3", label: "Q3", amount: 520 },
      { key: "q4", label: "Q4", amount: 450 },
    ],
    events: [
      { ticker: "AAPL", date: "2025-02-18", amountPerShare: 0.24, shares: 120, cashAmount: 28.8, currency: "USD" },
      { ticker: "MSFT", date: "2025-03-05", amountPerShare: 0.75, shares: 90, cashAmount: 67.5, currency: "USD" },
      { ticker: "JNJ", date: "2025-04-12", amountPerShare: 1.19, shares: 60, cashAmount: 71.4, currency: "USD" },
      { ticker: "V", date: "2025-05-02", amountPerShare: 0.52, shares: 80, cashAmount: 41.6, currency: "USD" },
    ],
  },
}

export const demoHoldings = {
  meta: {
    anyCostBasis: true,
    benchmark: "^GSPC",
    refreshedAt: "2025-12-07T09:00:00.000Z",
    avgBetaWeighted: 1.04,
  },
  holdings: [
    {
      id: "h1",
      ticker: "AAPL",
      quoteSymbol: "AAPL",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Technology",
      price: 195.12,
      weightPct: 12.5,
      shares: 80,
      hasCostBasis: true,
      returnSincePurchase: 28.5,
      contributionPct: 3.2,
      volatility12m: 22.4,
      beta12m: 1.12,
      riskScore: 42,
      riskBucket: "Medium",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 55, weight: 0.4, value: 22.4 },
        { key: "beta", label: "Beta", score: 44, weight: 0.3, value: 1.12 },
        { key: "size", label: "Size", score: 28, weight: 0.3, value: 2.8 },
      ],
    },
    {
      id: "h2",
      ticker: "MSFT",
      quoteSymbol: "MSFT",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Technology",
      price: 378.45,
      weightPct: 10.2,
      shares: 60,
      hasCostBasis: true,
      returnSincePurchase: 18.9,
      contributionPct: 2.1,
      volatility12m: 19.5,
      beta12m: 0.98,
      riskScore: 36,
      riskBucket: "Medium",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 41, weight: 0.4, value: 19.5 },
        { key: "beta", label: "Beta", score: 35, weight: 0.3, value: 0.98 },
        { key: "size", label: "Size", score: 25, weight: 0.3, value: 2.6 },
      ],
    },
    {
      id: "h3",
      ticker: "NVDA",
      quoteSymbol: "NVDA",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Technology",
      price: 512.3,
      weightPct: 9.4,
      shares: 35,
      hasCostBasis: true,
      returnSincePurchase: 46.7,
      contributionPct: 4.1,
      volatility12m: 37.5,
      beta12m: 1.32,
      riskScore: 68,
      riskBucket: "High",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 78, weight: 0.4, value: 37.5 },
        { key: "beta", label: "Beta", score: 71, weight: 0.3, value: 1.32 },
        { key: "size", label: "Size", score: 54, weight: 0.3, value: 1.1 },
      ],
    },
    {
      id: "h4",
      ticker: "GOOGL",
      quoteSymbol: "GOOGL",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Communication Services",
      price: 141.8,
      weightPct: 8.1,
      shares: 55,
      hasCostBasis: true,
      returnSincePurchase: 21.3,
      contributionPct: 1.8,
      volatility12m: 23.1,
      beta12m: 1.09,
      riskScore: 48,
      riskBucket: "Medium",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 52, weight: 0.4, value: 23.1 },
        { key: "beta", label: "Beta", score: 47, weight: 0.3, value: 1.09 },
        { key: "size", label: "Size", score: 35, weight: 0.3, value: 1.8 },
      ],
    },
    {
      id: "h5",
      ticker: "V",
      quoteSymbol: "V",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Financials",
      price: 254.2,
      weightPct: 6.8,
      shares: 40,
      hasCostBasis: true,
      returnSincePurchase: 12.4,
      contributionPct: 0.9,
      volatility12m: 16.8,
      beta12m: 0.92,
      riskScore: 29,
      riskBucket: "Low",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 30, weight: 0.4, value: 16.8 },
        { key: "beta", label: "Beta", score: 28, weight: 0.3, value: 0.92 },
        { key: "size", label: "Size", score: 27, weight: 0.3, value: 2.4 },
      ],
    },
    {
      id: "h6",
      ticker: "TSLA",
      quoteSymbol: "TSLA",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Consumer Discretionary",
      price: 244.9,
      weightPct: 5.6,
      shares: 25,
      hasCostBasis: true,
      returnSincePurchase: -8.4,
      contributionPct: -0.4,
      volatility12m: 44.1,
      beta12m: 1.48,
      riskScore: 77,
      riskBucket: "High",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 88, weight: 0.4, value: 44.1 },
        { key: "beta", label: "Beta", score: 82, weight: 0.3, value: 1.48 },
        { key: "size", label: "Size", score: 61, weight: 0.3, value: 0.9 },
      ],
    },
    {
      id: "h7",
      ticker: "JNJ",
      quoteSymbol: "JNJ",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Healthcare",
      price: 169.2,
      weightPct: 4.2,
      shares: 30,
      hasCostBasis: true,
      returnSincePurchase: 6.1,
      contributionPct: 0.3,
      volatility12m: 14.3,
      beta12m: 0.71,
      riskScore: 22,
      riskBucket: "Low",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 22, weight: 0.4, value: 14.3 },
        { key: "beta", label: "Beta", score: 19, weight: 0.3, value: 0.71 },
        { key: "size", label: "Size", score: 25, weight: 0.3, value: 2.0 },
      ],
    },
    {
      id: "h8",
      ticker: "XLE",
      quoteSymbol: "XLE",
      priceCurrency: "USD",
      localCurrency: "USD",
      sector: "Energy",
      price: 90.7,
      weightPct: 4.9,
      shares: 45,
      hasCostBasis: true,
      returnSincePurchase: 9.7,
      contributionPct: 0.5,
      volatility12m: 24.8,
      beta12m: 1.06,
      riskScore: 46,
      riskBucket: "Medium",
      riskComponents: [
        { key: "vol", label: "Volatility", score: 50, weight: 0.4, value: 24.8 },
        { key: "beta", label: "Beta", score: 46, weight: 0.3, value: 1.06 },
        { key: "size", label: "Size", score: 41, weight: 0.3, value: 1.6 },
      ],
    },
  ],
}

export const demoResearch: ResearchResponse = {
  result:
    "This demo portfolio mixes high-quality compounders with cyclical growth and dividend ballast. Semiconductors and software provide upside sensitivity to AI and enterprise spend, while defensives and dividends help smooth drawdowns across regimes.",
  tickers: ["ASML", "AMZN", "META", "TSM", "AVGO", "NVO", "BRK-B", "LMT"],
  generatedAt: "2025-12-15T09:05:00.000Z",
  insights: [
    {
      ticker: "ASML",
      overview: {
        name: "ASML Holding N.V.",
        Sector: "Information Technology",
        MarketCapitalization: 304_410_000_000,
        PERatio: 82.36,
        DividendYield: 0.0,
      },
      price: { changePercent1d: -0.18, fwdPE: 79.1, dividendYield: 0.0, epsGrowthYoy: 20.3 },
      earnings: { reportedEPS: 11.1, nextDate: "2026-01-22", surprise: "Beat 6 of last 8 quarters" },
      insiders: [],
      news: [
        {
          title: "EUV demand supports backlog despite cycle concerns",
          source: "Yahoo Finance",
          url: "#",
          summary: "Advanced-node transitions keep EUV shipments resilient; valuation remains elevated versus history.",
        },
        {
          title: "Semicap capex scrutiny rises into 2026 planning season",
          source: "Reuters",
          url: "#",
          summary: "Customers prioritize leading-edge tools while trimming trailing-edge spend; mix shift benefits EUV-heavy suppliers.",
        },
        {
          title: "ASML margin profile stays robust on service attach",
          source: "Bloomberg",
          url: "#",
          summary: "Service and software expansion supports gross margin; delivery cadence remains the key swing factor.",
        },
      ],
    },
    {
      ticker: "AMZN",
      overview: {
        name: "Amazon.com, Inc.",
        Sector: "Consumer Discretionary",
        MarketCapitalization: 1_920_000_000_000,
        PERatio: 54.8,
        DividendYield: 0.0,
      },
      price: { changePercent1d: 0.41, fwdPE: 39.6, dividendYield: 0.0, epsGrowthYoy: 34.2 },
      earnings: { reportedEPS: 1.24, nextDate: "2026-02-05", surprise: "Beat 5 of last 8 quarters" },
      insiders: [{ name: "Director", transactionType: "Buy", share: 1200, date: "2025-11-19" }],
      news: [
        {
          title: "AWS re-accelerates as AI workloads expand",
          source: "Reuters",
          url: "#",
          summary: "Cloud optimization headwinds fade; GenAI services lift consumption trends and attach rates.",
        },
        {
          title: "Retail margin improves on fulfillment efficiency",
          source: "Bloomberg",
          url: "#",
          summary: "Network regionalization and delivery density reduce unit costs; advertising continues to scale profitably.",
        },
        {
          title: "Advertising growth remains a key profit engine",
          source: "Yahoo Finance",
          url: "#",
          summary: "Higher-margin ad revenue offsets retail seasonality; competition remains the near-term watch item.",
        },
      ],
    },
    {
      ticker: "META",
      overview: {
        name: "Meta Platforms, Inc.",
        Sector: "Communication Services",
        MarketCapitalization: 1_380_000_000_000,
        PERatio: 29.4,
        DividendYield: 0.005,
      },
      price: { changePercent1d: 0.27, fwdPE: 25.8, dividendYield: 0.5, epsGrowthYoy: 22.7 },
      earnings: { reportedEPS: 5.12, nextDate: "2026-01-29", surprise: "Beat 7 of last 8 quarters" },
      insiders: [],
      news: [
        {
          title: "Ad pricing strengthens with improved targeting",
          source: "Reuters",
          url: "#",
          summary: "AI-driven ranking boosts engagement and conversion; capex remains elevated for infrastructure build-out.",
        },
        {
          title: "Reels monetization continues to narrow the gap",
          source: "Bloomberg",
          url: "#",
          summary: "Short-form ad load and better recommendation models lift revenue per impression.",
        },
        {
          title: "Meta increases shareholder returns amid strong cash flow",
          source: "Yahoo Finance",
          url: "#",
          summary: "Buybacks and dividend support total return; regulatory headlines remain a recurring overhang.",
        },
      ],
    },
    {
      ticker: "TSM",
      overview: {
        name: "Taiwan Semiconductor Manufacturing Company",
        Sector: "Information Technology",
        MarketCapitalization: 640_000_000_000,
        PERatio: 24.8,
        DividendYield: 0.016,
      },
      price: { changePercent1d: 0.36, fwdPE: 21.9, dividendYield: 1.6, epsGrowthYoy: 18.4 },
      earnings: { reportedEPS: 1.62, nextDate: "2026-01-16", surprise: "Beat 6 of last 8 quarters" },
      insiders: [],
      news: [
        {
          title: "Leading-edge node demand stays firm for AI accelerators",
          source: "Reuters",
          url: "#",
          summary: "Advanced packaging and N3/N2 ramp remain the main drivers; utilization stabilizes across key platforms.",
        },
        {
          title: "Capex discipline emphasized amid cycle normalization",
          source: "Bloomberg",
          url: "#",
          summary: "Management balances growth investments with margin targets; geopolitics remains the headline risk.",
        },
        {
          title: "TSMC expands advanced packaging capacity",
          source: "Yahoo Finance",
          url: "#",
          summary: "CoWoS and related capacity additions support GPU supply chains; ramp pace is closely watched by customers.",
        },
      ],
    },
    {
      ticker: "AVGO",
      overview: {
        name: "Broadcom Inc.",
        Sector: "Information Technology",
        MarketCapitalization: 930_000_000_000,
        PERatio: 33.9,
        DividendYield: 0.014,
      },
      price: { changePercent1d: 0.19, fwdPE: 28.7, dividendYield: 1.4, epsGrowthYoy: 15.6 },
      earnings: { reportedEPS: 10.2, nextDate: "2026-03-06", surprise: "Beat 6 of last 8 quarters" },
      insiders: [{ name: "CEO", transactionType: "Sell", share: 35000, date: "2025-10-03" }],
      news: [
        {
          title: "AI networking demand supports high-end connectivity",
          source: "Reuters",
          url: "#",
          summary: "Switching and interconnect exposure remains strong; customers prioritize bandwidth upgrades for training clusters.",
        },
        {
          title: "Software segment provides steadier cash flows",
          source: "Bloomberg",
          url: "#",
          summary: "Recurring revenue mix helps dampen semis cyclicality; integration execution stays in focus.",
        },
        {
          title: "Dividend growth continues alongside buybacks",
          source: "Yahoo Finance",
          url: "#",
          summary: "Capital returns remain attractive; valuation sensitive to enterprise spending and handset cycles.",
        },
      ],
    },
    {
      ticker: "NVO",
      overview: {
        name: "Novo Nordisk A/S",
        Sector: "Health Care",
        MarketCapitalization: 520_000_000_000,
        PERatio: 37.2,
        DividendYield: 0.012,
      },
      price: { changePercent1d: -0.08, fwdPE: 31.5, dividendYield: 1.2, epsGrowthYoy: 28.9 },
      earnings: { reportedEPS: 3.44, nextDate: "2026-02-07", surprise: "Beat 6 of last 8 quarters" },
      insiders: [],
      news: [
        {
          title: "GLP-1 demand remains strong as supply expands",
          source: "Reuters",
          url: "#",
          summary: "Capacity investments aim to reduce shortages; competition and pricing dynamics remain key watch items.",
        },
        {
          title: "Obesity and diabetes franchises extend multi-year runway",
          source: "Bloomberg",
          url: "#",
          summary: "Pipeline updates support long-duration growth thesis; reimbursement headlines can drive volatility.",
        },
        {
          title: "Margin resilience supported by mix and scale",
          source: "Yahoo Finance",
          url: "#",
          summary: "Higher-volume output improves absorption; near-term spend rises for manufacturing expansion.",
        },
      ],
    },
    {
      ticker: "BRK-B",
      overview: {
        name: "Berkshire Hathaway Inc.",
        Sector: "Financials",
        MarketCapitalization: 880_000_000_000,
        PERatio: 20.6,
        DividendYield: 0.0,
      },
      price: { changePercent1d: 0.09, fwdPE: 19.8, dividendYield: 0.0, epsGrowthYoy: 9.8 },
      earnings: { reportedEPS: 5.86, nextDate: "2026-02-24", surprise: "Beat 5 of last 8 quarters" },
      insiders: [],
      news: [
        {
          title: "Higher interest income boosts operating earnings",
          source: "Yahoo Finance",
          url: "#",
          summary: "Large cash balances benefit from elevated yields; underwriting discipline remains a stabilizer.",
        },
        {
          title: "Buyback pace tied to valuation and opportunity set",
          source: "Bloomberg",
          url: "#",
          summary: "Capital allocation remains flexible; market volatility can create attractive entry points for deployments.",
        },
        {
          title: "Insurance results remain the core earnings anchor",
          source: "Reuters",
          url: "#",
          summary: "Cat losses fluctuate but pricing conditions supportive; investment income trends stay favorable.",
        },
      ],
    },
    {
      ticker: "LMT",
      overview: {
        name: "Lockheed Martin Corporation",
        Sector: "Industrials",
        MarketCapitalization: 112_000_000_000,
        PERatio: 16.9,
        DividendYield: 0.027,
      },
      price: { changePercent1d: 0.12, fwdPE: 15.2, dividendYield: 2.7, epsGrowthYoy: 6.4 },
      earnings: { reportedEPS: 27.5, nextDate: "2026-01-21", surprise: "Beat 6 of last 8 quarters" },
      insiders: [{ name: "CFO", transactionType: "Buy", share: 600, date: "2025-09-14" }],
      news: [
        {
          title: "Backlog visibility supports steady cash generation",
          source: "Yahoo Finance",
          url: "#",
          summary: "Multi-year program funding provides resilience; execution and supply chain remain key variables.",
        },
        {
          title: "Defense budgets prioritize air and missile defense",
          source: "Reuters",
          url: "#",
          summary: "International demand offsets domestic timing; margins supported by high-value programs.",
        },
        {
          title: "Dividend coverage remains healthy with buybacks",
          source: "Bloomberg",
          url: "#",
          summary: "Shareholder returns steady; program milestones and contract awards drive near-term sentiment.",
        },
      ],
    },
  ],
  stories: [
    { ticker: "ASML", summary: "EUV tool dominance keeps structural edge, but valuation is sensitive to semicap cycles and deliveries." },
    { ticker: "TSM", summary: "Leading-edge and advanced packaging demand stays strong; geopolitics remains the headline risk." },
    { ticker: "AVGO", summary: "AI networking and software cash flows create a blend of growth and durability." },
    { ticker: "AMZN", summary: "AWS re-acceleration and advertising mix lift margins; retail efficiency remains an upside lever." },
    { ticker: "META", summary: "AI-driven engagement and better ad tooling support monetization; capex is the key trade-off." },
    { ticker: "NVO", summary: "GLP-1 franchise supports long runway; supply expansion and pricing competition are the swing factors." },
    { ticker: "BRK-B", summary: "Cash yields and disciplined underwriting steady returns; deployment optionality rises in volatility." },
    { ticker: "LMT", summary: "Backlog and dividends provide defensiveness; execution and funding cadence drive near-term moves." },
  ],
  meta: { model: "demo-mock", lookbackDays: 45, tickerCount: 8, status: "complete" },
}


export const demoSummary: SummaryResp = {
  overall: {
    score: 86,
    components: [
      {
        key: "allocation",
        label: "Allocation",
        weight: 0.25,
        score: 84,
        scorePct: 84,
        contribution: 21,
        rationale: ["Tech overweight drives growth", "Energy sleeve provides inflation hedge"],
      },
      {
        key: "risk",
        label: "Risk",
        weight: 0.25,
        score: 82,
        scorePct: 82,
        contribution: 21,
        rationale: ["Beta near 1.0 keeps market tracking", "Top position under 10%"],
      },
      {
        key: "performance",
        label: "Performance",
        weight: 0.25,
        score: 90,
        scorePct: 90,
        contribution: 23,
        rationale: ["Outperformed benchmark YTD", "Positive contribution from 7 of 8 holdings"],
      },
      {
        key: "quality",
        label: "Quality",
        weight: 0.25,
        score: 88,
        scorePct: 88,
        contribution: 22,
        rationale: ["High ROIC businesses dominate", "Limited leverage across holdings"],
      },
    ],
    drivers: {
      positives: ["AI and cloud exposure", "Defensive ballast via healthcare and energy", "Healthy dividend stream"],
      negatives: ["Growth tilt raises valuation risk", "Limited small-cap exposure"],
    },
  },
  summaryMetrics: {
    totalReturnPct: 18.4,
    holdingsCount: 18,
    sharpeRatio: 1.28,
    hasMeaningfulCostBasis: true,
  },
}
